import os
os.system ('clear')
os.system ('clear')
os.system ('sl')
os.system ('clear')
os.system ('figlet FREE FIRE ')
print ("")
print ("")
print ("  moadmaodxzone@gmail.com")
print ("  youssef1928oz")
print ("")
print ("   alizikozxzone@gmail.com")
print ("   REDA@BADR2023")
print ("")
print ("")
print ("   aminemkaloi2018@gmail.com")
print ("   freefire2017AZERT")
print ("")
print ("   100041328683866")
print ("   +20155 627 8547")
print ("   Ibrahim@@vidaloka")
os.system ('figlet')
