import os
os.system ('clear')
os.system ('clear')
os.system ('sl')
os.system ('clear')
os.system ('figlet FREE FIRE ')
print ("")
print ("")
print ("  moadmaodxzone@gmail.com")
print ("  youssef2009FAML")
print ("")
print ("   alizikozxzone@gmail.com")
print ("   REDA@@MAROUIIIIIIM")
print ("")
print ("")
print ("   0652421939")
print ("   youssef2009 ")
print ("0809 1043 9875 1669 ")
print ("")
print ("   +20155 627 8547")
print ("   Egybet2039mirob")
print ("")
print ("")
print ("   wadieaw94@gmail.com")
print ("   zokmok18cc")
print("\033[91mYou have been permanently banned because you used more than 4 opportunities\033[0m")
print("\033[91mYou have been permanently banned because you used more than 4 opportunities\033[0m")
print("\033[91mYou have been permanently banned because you used more than 4 opportunities\033[0m")
print("\033[91mYou have been permanently banned because you used more than 4 opportunities\033[0m")
print("\033[91mYou have been permanently banned because you used more than 4 opportunities\033[0m")
print("\033[91mYou have been permanently banned because you used more than 4 opportunities\033[0m")
print("\033[91mYou have been permanently banned because you used more than 4 opportunities\033[0m")
print("\033[91mYou have been permanently banned because you used more than 4 opportunities\033[0m")
print("\033[91mYou have been permanently banned because you used more than 4 opportunities\033[0m")
print("\033[91mYou have been permanently banned because you used more than 4 opportunities\033[0m")
print("\033[91mYou have been permanently banned because you used more than 4 opportunities\033[0m")
print("\033[91mYou have been permanently banned because you used more than 4 opportunities\033[0m")
print("\033[91mYou have been permanently banned because you used more than 4 opportunities\033[0m")
print("\033[91mYou have been permanently banned because you used more than 4 opportunities\033[0m")
print("\033[91mYou have been permanently banned because you used more than 4 opportunities\033[0m")
print("\033[91mYou have been permanently banned because you used more than 4 opportunities\033[0m")
print("\033[91mYou have been permanently banned because you used more than 4 opportunities\033[0m")
print("\033[91mYou have been permanently banned because you used more than 4 opportunities\033[0m")
print("\033[91mYou have been permanently banned because you used more than 4 opportunities\033[0m")
print("\033[91mYou have been permanently banned because you used more than 4 opportunities\033[0m")
print("\033[91mYou have been permanently banned because you used more than 4 opportunities\033[0m")
print("\033[91mYou have been permanently banned because you used more than 4 opportunities\033[0m")
print("\033[91mYou have been permanently banned because you used more than 4 opportunities\033[0m")
os.system ('figlet')
